name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Variables
        run: |
          echo "AZURE_LOCATION=$(echo ${{ secrets.AZURE_LOCATION }} | sed 's/./& /g')"
          echo "AZURE_ENV_NAME=$(echo ${{ secrets.AZURE_ENV_NAME }} | sed 's/./& /g')"

      - name: Replace AZURE_ENV_NAME in Parameters File
        run: |
          sed -i 's|${AZURE_ENV_NAME}|${{ secrets.AZURE_ENV_NAME }}|g' ./infra/main.parameters.json

      - name: Replace AZURE_LOCATION in Parameters File
        run: |
          sed -i 's|${AZURE_LOCATION}|${{ secrets.AZURE_LOCATION }}|g' ./infra/main.parameters.json

      - name: Replace OPENAI_CAPACITY in Parameters File (Ensure Integer)
        run: |
          sed -i 's|"value": "${OPENAI_CAPACITY}"|"value": '${{ secrets.OPENAI_CAPACITY }}'|g' ./infra/main.parameters.json

      - name: Replace ENTRA_AUTH in Parameters File (Ensure Boolean)
        run: |
          sed -i 's|"value": "${AZURE_ENTRA_AUTH}"|"value": '${{ secrets.AZURE_ENTRA_AUTH }}'|g' ./infra/main.parameters.json

      - name: Deploy Bicep file
        run: |
          az deployment sub create \
            --location "${{ secrets.AZURE_LOCATION }}" \
            --template-file ./infra/main.bicep \
            --parameters ./infra/main.parameters.json
